# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-17 10:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gmina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('rodzaj', models.CharField(choices=[(b'miasto', b'miasto'), (b'wies', b'wies'), (b'statek', b'statek'), (b'zagranica', b'zagranica')], max_length=15)),
                ('liczba_mieszkancow', models.IntegerField()),
                ('liczba_uprawnionych', models.IntegerField()),
                ('liczba_wydanych_kart', models.IntegerField()),
                ('liczba_glosow_oddanych', models.IntegerField()),
                ('data_modyfikacji', models.DateTimeField()),
                ('uzytkownik_modyfikujacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'gminy',
            },
        ),
        migrations.CreateModel(
            name='Kandydat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'gminy',
            },
        ),
        migrations.CreateModel(
            name='Wojewodztwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'wojewodztwa',
            },
        ),
        migrations.CreateModel(
            name='Wyniki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liczba_glosow', models.IntegerField()),
                ('gmina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyniki.Gmina')),
                ('kandydat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyniki.Kandydat')),
            ],
            options={
                'verbose_name_plural': 'wyniki',
            },
        ),
        migrations.AddField(
            model_name='gmina',
            name='wojewodztwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyniki.Wojewodztwo'),
        ),
        migrations.AlterUniqueTogether(
            name='wyniki',
            unique_together=set([('kandydat', 'gmina')]),
        ),
    ]
