# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-29 20:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki', '0002_auto_20160817_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmina',
            name='data_modyfikacji',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
