# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki', '0003_auto_20160829_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmina',
            name='rodzaj',
            field=models.CharField(choices=[('miasto', 'miasto'), ('wies', 'wies'), ('statek', 'statek'), ('zagranica', 'zagranica')], max_length=15),
        ),
    ]
