# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki', '0004_auto_20160829_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmina',
            name='data_modyfikacji',
            field=models.DateTimeField(blank=True),
        ),
    ]
